# Generated by Django 3.2.20 on 2023-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='miNTq2iMU7eq0wJ', editable=False, max_length=10),
        ),
    ]
